--- SCRIPT PARA INICIAR EL SETUP DEL ENTORNO

USE ROLE ACCOUNTADMIN;

-- creacion del role
CREATE ROLE IF NOT EXISTS DBT_ROLE;

-- creacion del warehouse
CREATE WAREHOUSE IF NOT EXISTS DBT_WH 
  WAREHOUSE_SIZE = 'X-SMALL';

-- creacion de la base de datos
CREATE DATABASE IF NOT EXISTS PROPELLING_TECH_DB;

-- asignar permisos
GRANT USAGE ON WAREHOUSE DBT_WH TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON DATABASE PROPELLING_TECH_DB TO ROLE DBT_ROLE;
GRANT CREATE SCHEMA ON DATABASE PROPELLING_TECH_DB TO ROLE DBT_ROLE;

-- asignar el rol a mi ususario
GRANT ROLE DBT_ROLE TO USER CARLOTAVILA;


SELECT * FROM PROPELLING_TECH_DB.BRONZE.raw_orders LIMIT 10;